### ISSUE TITLE
Handle wrongly typed body properties in backend API routes

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#122]
Ref: https://github.com/joulev/ezkomment/pull/121#discussion_r900274726

**Comment by joulev** [comment]
While we are at it, it is probably also a nice idea to post-process user-uploaded photos/images (e.g. check whether they are really photos or some malicious files, crop those photos to square size, reduce photo size, etc.)

**Comment by VietAnh1010** [comment]
To check whether the files are really photos or not, we just need to check the `minetype`. If it is not a valid `minetype`, we will reject the request.

I currently don't have any idea to crop and compress the photo, will look up the methods to do it later.

**Comment by joulev** [comment]
Yes it should not be prioritised.
