### ISSUE TITLE
Prevent against creating sites with the same name

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#124]
It is not yet handled.

```
Some uncaught error happened?
Error: 6 ALREADY_EXISTS: Document already exists: projects/ezkomment-dev/databases/(default)/documents/users/59HGBQJt6JZaNt3tQzC9xN9lO762/sites/blog-app
    at Object.callErrorFromStatus (/Users/joulev/dev/www/ezkomment/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/Users/joulev/dev/www/ezkomment/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
    at Object.onReceiveStatus (/Users/joulev/dev/www/ezkomment/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/Users/joulev/dev/www/ezkomment/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /Users/joulev/dev/www/ezkomment/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 6,
  details: 'Document already exists: projects/ezkomment-dev/databases/(default)/documents/users/59HGBQJt6JZaNt3tQzC9xN9lO762/sites/blog-app',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient'
}
```

**Comment by VietAnh1010** [comment]
Actually it is implemented, but I haven't configured the message yet.

The idea is that when a site is created, we also try to create a new document that uses the site's name as key. If a document exists, the creation will fail, making the entire transaction fail and as a result, the site will not be created.

**Comment by VietAnh1010** [comment]
Look at the `code 6`, I handled that right after the PR.

**Comment by joulev** [comment]
1. Well, that commit is absolutely unrelated to testing your backend. Now you need to try to find ways to get that commit to `main`, otherwise I can't use it.
2. I don't think that method is really efficient. What if the user wants to edit the site name (which we should allow, just like how we can edit GitHub repository name)? I would rather simply edit a field in the object than moving the object in whole to a different document.
3. [I think 409 would be the best status code for this case.](https://stackoverflow.com/a/3826024) Not often used, I know, but from its wording its the most RESTful one we have.

**Comment by VietAnh1010** [comment]
> Well, that commit is absolutely unrelated to testing your backend. Now you need to try to find ways to get that commit to main, otherwise I can't use it.

I guess I have to commit directly to `main`. I discovered `code 6` when I messing around.

> I don't think that method is really efficient. What if the user wants to edit the site name (which we should allow, just like how we can edit GitHub repository name)? I would rather simply edit a field in the object than moving the object in whole to a different document.

Well, how should I explain it?

- We will maintain 2 collections, `sites` and `users`.
- When we create a new site:
  - In the `sites` collection, we will create a document to store the site's information. The path to this document will be: `sites/[siteId]`.
  - In the `users/[uid]/sites` collection (I will use a nested collection here), we will create another document, with the site's name as key. The path to this document will be `users/[uid]/sites/[siteName]`. Note that we don't have to store any information in this document, it acts as a placeholder to signify that `siteName` has been taken for user `[uid]`.
- To update the name, we just need to remove `users/[uid]/sites/[oldSiteName]` and create `users/[uid]/sites/[newSiteName]`. If `newSiteName` is taken, the update will fail (these operations are done in a transaction, so if the create is not executed then the delete will not be executed as well).

> I think 409 would be the best status code for this case. Not often used, I know, but from its wording it's the most RESTful one we have.

Nice, I was wondering what is the best status code for this situation.

**Comment by joulev** [comment]
> we just need to remove users/[uid]/sites/[oldSiteName] and create users/[uid]/sites/[newSiteName]

*That* is exactly where it is not efficient. Instead of modifying a record you are essentially recreating that record which is arguably worse.

**Comment by VietAnh1010** [comment]
That record stores very little information, so recreating that is not too costly.

Another solution is to use an array, but look-up in array is slower.

**Comment by joulev** [comment]
Sorry forgot to close this. This has been fixed long ago.
