### ISSUE TITLE
Include list of all site IDs under a user in the user object

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#125]
Currently retrieving user information only includes the `User` Firebase object.

I realise that almost all the time, I need to make a secondary call to `/api/users/:uid/sites` to get the site list, since otherwise I can't know the `siteId` needed for API calls.

Considering the list of site IDs is pretty small, I think it is more efficient for the user information (retrieved from `GET /api/users/:uid`) to also include the site IDs. Something like

```json5
{
  // ...auth.currentUser,
  sites: [
    {
      name: "blog-app",
      id: "abcde"
    },
    // ...
  ]
}
```

or

```json5
// is this better?
{
  // ...auth.currentUser,
  sites: {
    "blog-app": "abcde",
    // ...
  }
}
```

This is also where `GET /api/users/:uid` would actually make any sense, since the `UserRecord` Firebase object is already retrieved with the Firebase client library.

**Comment by joulev** [comment]
I'd suggest working on it immediately (since it probably won't take much time) so that I don't have to turn to less efficient methods of data fetching as placeholders.

**Comment by joulev** [comment]
Hmm I have found a way to still fetch data efficiently while not requiring the backend to do this, however do consider this proposal and implement it if it makes sense to you. Otherwise you can simply close the issue.

**Comment by VietAnh1010** [comment]
Haha, I realize that the method to prevent duplicate site names turns out to be really helpful in this case.

I will get the data from the nested collection `users/[uid]/sites` as well. And it should be faster as we just need to get all the from that nested collection, without doing any complex query at all.
