### ISSUE TITLE
Allow updating domains for the sites

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#126]
> Site's domain cannot be updated (how will the pages be handled in that case?). &mdash; [PUT `/sites/:siteId` spec](https://github.com/joulev/ezkomment/wiki/Internal-API-specs#put-sitessiteid)

Is there any special handling for pages under a domain? I was planning to use this domain for [`frame-ancestors`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors), so it is simply an HTTP header that we send to clients and can be changed easily.

So I suggest configuring the backend in such a way that allows updating domains (and pretty much all metadata) of sites.

**Comment by VietAnh1010** [comment]
Hmm, the question is that the page's URL must match the site's domain. Update the site's domain means that we have to update the page's URL as well.

Let me think of a way to effectively do this.

**Comment by joulev** [comment]
> Hmm, the problem is that the page's URL must match the site's domain. Update the site's domain means that we have to update the page's URL as well.
> 
> Let me think of a way to effectively do this.

Remove that restriction. We don't need to be too restrictive, page URL is only for identification purposes and from the security's point of view, we don't need this restriction.

I will check for the page URL on client-side and give the user a warning. I think that's enough.

**Comment by VietAnh1010** [comment]
Done. I pushed the fix to `main`.

**Comment by joulev** [comment]
Nice. FYI you can also use closing keywords to automatically close this issue after committing.

> You can link a pull request to an issue by using a supported keyword in the pull request's description **or in a commit message** (emphasis is mine). The pull request must be on the default branch. &mdash; [source](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

e.g.

```sh
git commit -S -s -m "allow updating site domain, fix #126"
```
