### ISSUE TITLE
Delete old photo after uploading new ones

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#127]
It appears to me (I haven't digged to backend source) that the backend doesn't update old photos in the storage with new photos as new ones are updated.

![Screen Recording 2022-06-20 at 11 04 14](https://user-images.githubusercontent.com/44609036/174523472-086dba3d-6c29-473f-b13c-850743c43dcd.gif)

It can change profile picture from the default picture (from GitHub or Google) to the uploaded picture (Firebase Storage), however it apparently can't change from one uploaded picture to another uploaded picture.

Please have a look. I say *apparently* because it may be a frontend bug (which I think is unlikely). For now I will add the [bug] label.

**Comment by joulev** [comment]
Steps to reproduce:

* Go to https://test.joulev.dev, log in there
* If your `photoURL` is the default photo from GitHub or Google, upload a new one
* Upload another profile photo

**Comment by joulev** [comment]
It now *appears* that the photos are indeed updated but for some reasons, the public URL doesn't point to the new photo immediately. In fact, it takes quite long, and it isn't due to caching either (I opened the link in a new browser and it still shows the old photo).

![Screen Recording 2022-06-20 at 13 03 27](https://user-images.githubusercontent.com/44609036/174535915-a96ff801-4873-4628-a46c-ea803c0e69fe.gif)

**Comment by VietAnh1010** [comment]
I used `{ metadate: { firebaseStorageDownloadTokens: <token> } }` to manually set the token and recreate the download URL.

This is not a documented feature 😰 But it was the best solution available.
