### ISSUE TITLE
Make the API routes more RESTful

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#133]
This supersedes #125. I think we can design the backend routes to be a bit more RESTful. This issue excludes comment routes which are not yet documented in the API specs.

### Route renames

| From | To |
|:--|:--|
| POST `/users/:uid/sites` | POST `/sites` |
| POST `/sites/:siteId/pages` | POST `/pages` (with `sideId` inside body) |

### Route merges

To make code like this more concise:

https://github.com/joulev/ezkomment/blob/63c439cbe5d1982b22403de948e53599176926d6/client/lib/firebase/auth.ts#L59-L68

We have no reasons to keep them in different routes anyway.

| Route | Merge to body of |
|:--|:--|
| GET `/users/:uid/sites` | GET `/users/:uid` |
| GET `/sites/:siteId/pages` | GET `/sites/:siteId` |

**Comment by joulev** [comment]
Hmm I suggest prioritising this, especially the merging section, and completing it asap so that I don't have to make my own types like this

https://github.com/joulev/ezkomment/blob/63c439cbe5d1982b22403de948e53599176926d6/types/client/auth.type.ts#L8

Also I suggest exporting the `User`, `Site`, `Page` types with this route design so that I can import them directly instead of writing myself (which ensures client typing and server typing are consistent).

**Comment by VietAnh1010** [comment]
For GET `/users/:uid` and GET `/sites/:siteId`, what information about the sites and the pages should be included in the responses?

Are the ids enough? Or should more information be returned?

I will commit these directly into the `test-be-with-fb-emulator` branch` as I completed writing unit tests for my utilities. 

Should be able complete this pretty fast. I will open a PR later today.

**Comment by VietAnh1010** [comment]
> Also I suggest exporting the User, Site, Page types with this route design so that I can import them directly instead of writing them myself (which ensures client typing and server typing are consistent).

I will export them as `ClientUser`, `ClientSite` and `ClientPage`.

**Comment by VietAnh1010** [comment]
[x]: Implemented `pageCount` for sites. Pretty simple.
[ ]: Implemented `totalCommentCount` and `pendingCommentCount` for sites.
[ ]: Implemented `totalCommentCount` and `pendingCommentCount` for pages.

I will change the names of some fields to make them more consistent and easier to remember.

Implementing statistics about the last 30 days is difficult (operations on array in Firebase are very restricted), I will not implement these features in this PR.

**Comment by VietAnh1010** [comment]
We will only allow "pending" comment to be updated to "approved" comment and not vice-versa, right?

This would simplify the implementation a lot.

**Comment by joulev** [comment]
Yes, that's correct.
