### ISSUE TITLE
[CRITICAL] If an attacker has the site id of the targeted site, he can do literally everything

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#137]
We are lucky that this app is not really released for use yet. And I am utterly embarrassed at myself for not realising this earlier.

Current implementation is that whenever a user makes a request to `/api/sites/:siteId`, while we check for the user token, we never verify whether that user is allowed to get/update/delete the site with `siteId`.

So if I have the `siteId` of a site, I can very simply send a request `/api/sites/:siteId` and all will succeed even though that site isn't mine.

![Screen Recording 2022-06-22 at 13 35 56](https://user-images.githubusercontent.com/44609036/174961035-ce5993f6-e768-4cb6-8e46-8f525cd780bc.gif)

This requires immediate hotfix. We always have to assume there is some attackers who know all details about Firebase Client SDK API key (it's literally searchable from the source), all UID, all site ID, etc. and can make malicious requests at any time. They only don't have Firebase Admin SDK credentials.

**Comment by joulev** [comment]
For extra security, for all requests please check whether the user is authorised to perform the intended action, even if we can decode the token to a valid user.

And yes, we can search for the Firebase API key from source sent to client. See here:

<img width="1093" alt="Screenshot 2022-06-22 at 13 48 54" src="https://user-images.githubusercontent.com/44609036/174962405-8a1fce26-7411-4684-9693-0483539d3643.png">

**Comment by VietAnh1010** [comment]
If I am correct, the API key will be the same for anybody. So search for the API key is not enough.

We neeed to check for some information and match it with the decoded information, and the operation should be fast. I need some idea with this.

**Comment by joulev** [comment]
For the case of sites, I think we already store the `uid` of the owner in the site object? Then I think simply comparing that `uid` with the decoded ID token is enough. Similar for the case of pages. I think including the owner `uid` field in all objects (at least on the server) is a good idea.

For ease of development I suggest in your verify JWT function, you add the `uid` to the body after verifying. That will not only make it no longer necessary to include the `uid` in the body, but also make verifying permission much easier.

**Comment by VietAnh1010** [comment]
Noted. Will resolve this tonight

**Comment by VietAnh1010** [comment]
I will resolved this in a different branch. Should be able to open a PR soon, as this is not difficult &ndash; but quite easy to mess up.

**Comment by VietAnh1010** [comment]
Pretty much done it. 

I had to attend some other work previously, so the PR will be open quite late.

**Comment by joulev** [comment]
Don’t worry I’ll have a look tomorrow.
