### ISSUE TITLE
Should allow creation of pages with the same name

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#139]
The names aren't technically *name*, they are *title*, i.e. title of the blog post, or anything meaningful that the user will use for identification.

The URL will be `https://ezkomment.joulev.dev/app/site/<siteName>/<pageId>`, hence only `siteName` is required to be unique (`pageId` is always unique).

Therefore `pageName` doesn't need to be unique. We will identify a page with its never-changing `pageId` and that `pageId` only &ndash; `name` and `title` are only metadata accompanying the page.

`name` may even include special characters that Firebase might not accept as document name.

Therefore please modify the `/api/pages` route so that creating pages with same name is possible.

This is the inverted version of #124.

---

(also if possible could you also change from `name` to `title` in all variable names? Because it's more semantically correct and it will be consistent with frontend user-facing language.)

**Comment by VietAnh1010** [comment]
Noted, should be pretty easy to change this

**Comment by VietAnh1010** [comment]
Finally having some time to start working.

> (also if possible could you also change from name to title in all variable names? Because it's more semantically correct and it will be consistent with frontend user-facing language.)

From this, `name` should be replaced by `title` right?

`title` will be a string, and without the restriction that `title` should be unique, then `title` can include any character.

**Comment by joulev** [comment]
Yes that's correct.
