### ISSUE TITLE
Reconfigure test secrets so that Dependabot tests also pass

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#155]
Currently many Dependabot PRs are failing the backend tests because they don't have access to the Action secrets.

<img width="617" alt="image" src="https://user-images.githubusercontent.com/44609036/175917062-3a0d8783-abfc-41e3-a704-0546aaa7f57c.png">

But we cannot expose these secrets since, well, they are secrets for a reason.

I will have a look and see whether the emulator can run without certain secrets (that we must not expose) and reconfigure GitHub Actions.

Don't ask me why two PRs still managed to pass here &ndash; I don't know either.

**Comment by VietAnh1010** [comment]
I retried two PR to see their debug logs &ndash; the secrets can still be accessed during the retries.

I don't know why this is the case?

**Comment by joulev** [comment]
> I don't know why this is the case?

See my last sentence: "Don't ask me why two PRs still managed to pass here – I don't know either."

The next Dependabot updates will not arrive until next Monday, so this is definitely not urgent. I will have a look later this week.
