### ISSUE TITLE
Implement /api/embed/:siteId/:pageId

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#156]
Currently the page `/embed/:siteId/:pageId` is routed to `/api/embed/:siteId/:pageId`. Right now it has this dummy content

https://github.com/joulev/ezkomment/blob/679b5718aaaa9d11a8fd9748b85fe4d18060ff7e/pages/api/embed/%5BpageId%5D/%5BsiteId%5D.ts#L1-L12

which basically generate a HTML based on an API route URL (`/api/test`), then serve that HTML. Comments will be `GET`ed and `POST`ed to that route (see the dummy file `pages/api/test.ts` for slightly more info).

Now I transfer this embed file for you to maintain it from now on. We need to do the following to make it commentable:

* A public route to `GET` and `POST` comment for a particular `siteId` and `pageId` (or only `pageId` if you feel like it)
* Remove `pages/api/test.ts` and substitute `/api/test` in the embed endpoint to the route you just created
* For `[pageId]/[siteId].ts`, rename it to `[siteId]/[pageId].ts` (wtf was I doing when naming this thing) then we will probably need to verify that `siteId` and `pageId` exists before serving. I think we will only need the `GET` method for this route.

After doing this I think we will complete [the first (out of 4) item](https://ezkomment.joulev.dev/orbital/ms2-readme#going-forwards-to-milestone-3-25-july) in the plan until MS3.

**Comment by VietAnh1010** [comment]
Question: why do we need `siteId` in the path params?

**Comment by joulev** [comment]
You can remove it if you feel like doing so, since it is not necessary... but I think it would make the URL slightly more unguessable.
