### ISSUE TITLE
Render comments correctly in /app/site/:siteName/:pageId

### ISSUE THREAD

**Issue by VietAnh1010** [joulev/ezkomment#160]
Currently, in `/app/site/:siteName/:pageId`, the comments are not rendered correctly after being compiled to html.

![image](https://user-images.githubusercontent.com/91171052/177003611-b0078a50-0a18-4bd3-9144-15eb0c85dbce.png)

And by the way, the content of the empty comment is `<script>alert("Hacked");</script>`

**Comment by joulev** [comment]
> And by the way, the content of the empty comment is `<script>alert("Hacked");</script>`

Nice, that means XSS protection is good. Probably it would be nicer to have it rendered as `&lt;script&gt;alert("Hacked");&lt;/script&gt;` instead. I think Unified has a way to do this, I will have a look tomorrow. Otherwise the frontend will render as "no comment body".
