### ISSUE TITLE
Add statistic about the number of comments during the last 30 days

### ISSUE THREAD

**Issue by VietAnh1010** [joulev/ezkomment#178]
![image](https://user-images.githubusercontent.com/91171052/177345864-aedae817-6025-483a-bbc5-2d37660ed59a.png)

Currently the data is just 30 zeroes. How should I implement this feature now?

**Comment by joulev** [comment]
There may be a better/more efficient  approach but I think this can work:

You record relevant information (new comment added on `Timestamp`, new comment approved on `Timestamp`) to an internal array in the database. Then when I request the data for the graph, you parse that array to give relevant numbers for the last 30 days (and remove more-than-30-day-old data if you want).

Put it to a separate route (or configure the routes so that this parsing isn’t executed when I load the overall dashboard).

**Comment by VietAnh1010** [comment]
Let's start working on this.

**Comment by joulev** [comment]
We also have a notification sidebar too, might be good to combine both? since both have more or less the same information.

**Comment by VietAnh1010** [comment]
I am not sure about whether we should combine them at the moment, as I am still looking for a good implementation.

I will decide about this matter later after I complete the initial design

**Comment by VietAnh1010** [comment]
@joulev Currently I don't have any solution to _effectively_ record the total number of comments during the last 30 days.

We may not be able to delete old data if we want to report the total number of comments over time.

**Comment by joulev** [comment]
I don't think we need to delete old data.

A typical notification sidebar would be something like this

https://github.com/joulev/ezkomment/blob/ffe5afb769133cb04a1eeb02f69523afe6d6bdfc/client/components/app/notification.tsx#L28-L46

<img width="422" alt="image" src="https://user-images.githubusercontent.com/44609036/180197134-d501aa8c-4d3a-496e-9486-612bd43ffbbe.png">

so we will need to *persist* a history entry in the database.

**Comment by joulev** [comment]
> Notifications store information about page (if I am correct), not site.

hmm it actually makes sense. I forgot the scopes of the two.

> For site statistic, I haven't come up with a good design.

We don't need to make everything as efficient as possible. We can improve this later anyway.

**Comment by VietAnh1010** [comment]
The easiest solution for sites is to just querry all comments (as all comments has `siteId` as a property, and then parse them.

I guess I will go with this solution at the moment.
