### ISSUE TITLE
Feature 2: Moderation

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#179]
This issue tracks the development of the backend for moderation feature. (I don't think the frontend will have a lot of work to do, namely only rendering the pending comment array and toggle comment `approved` state).

* [x] UI (#180)
* [x] Approve all comments on auto-approve turned on
* [x] Remove pending comments from the public page

**Comment by VietAnh1010** [comment]
I have already implemented this.

When a comment is posted, we will look up the auto-approve of the page. If it is true then we will approve the comment, or else push it into the pending queue.

The main question right now is: when the auto-approve is switched from off to on, should all pending comments be approved as well?

**Comment by joulev** [comment]
> The main question right now is: when the auto-approve is switched from off to on, should all pending comments be approved as well?

Yes.

**Comment by joulev** [comment]
I just tested and yeah, it is working. One glitch though (other than the auto-approve off → on as you said), the public comment section appears to also show pending comments:

<img width="828" alt="image" src="https://user-images.githubusercontent.com/44609036/177962144-b1ee053a-71e3-417e-a284-211a6a569004.png">

<img width="645" alt="image" src="https://user-images.githubusercontent.com/44609036/177962199-04a3ee44-0205-492e-a244-e2705051ce6f.png">

**Comment by VietAnh1010** [comment]
I did not filter out comment with pending status. I will add this feature.

**Comment by joulev** [comment]
In conjunction with #180, this is all what we need for this feature (I think).

**Comment by VietAnh1010** [comment]
Finished the implementation. But I need to test it.
