### ISSUE TITLE
Remaining things to do before app completion

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#212]
This will supersede #50 and #51 (those two are way too outdated already).

* [x] Public API (#215)
* [x] Site statistics (#178)
* [x] Notifications (#225)
* [x] Export user data
* [x] Export site data
* [x] Export page data
* [x] Public documentation (#177)
* [x] ~~Optimise the public REST API while still following DRY~~ (feature dropped, it is not worth the complication)

**Comment by VietAnh1010** [comment]
What data will we export, in particular? And in which format?

**Comment by joulev** [comment]
All data basically, in JSON as usual. If `DELETE` deletes something then the exported data should have it. I could have chained a few fetches together to construct the JSON on frontend but it would require repeated network requests and token validations, which is arguably very slow.

**Comment by VietAnh1010** [comment]
> If DELETE deletes something then the exported data should have it.

Quite difficult. I will need a log for this.

**Comment by joulev** [comment]
Something like a recursive `GET` I think. Basically all data associated to the user/site/page.

**Comment by VietAnh1010** [comment]
> Something like a recursive GET I think. Basically all data associated to the user/site/page.

If we only do recursive GET, this is simple.

But if we also export **deleted** data, then it will become quite difficult to implement. I don't think I will support this.

Deleted data should be gone after we delete them, just like:

![image](https://user-images.githubusercontent.com/91171052/180475950-c0655852-5171-4484-bcad-1be378db88dd.png)

**Comment by joulev** [comment]
Yeah I was meaning that it is simply a recursive GET glorified.

**Comment by joulev** [comment]
@VietAnh1010 hmm I suggest we should priorities the public API first since it's the last core feature &ndash; if we finish it before next Monday we can proudly write "we have finished all planned features before ms3" in the readme.

**Comment by VietAnh1010** [comment]
Agree.

What are the requirements for the public API?

**Comment by joulev** [comment]
Not much. I think at the current state, we only need to copy the code for these public routes

https://github.com/joulev/ezkomment/blob/659ca711a74d71c55bcd34b10c2aee88a860a95d/pages/api/embed/%5BsiteId%5D/%5BpageId%5D.ts#L20-L24

to a route under version control (`/api/v1/*`), with the `GET` section having pagination. [More info](https://ezkomment.joulev.dev/orbital/ms2-readme#application-programming-interface).

**Comment by joulev** [comment]
Any progress updates?

**Comment by VietAnh1010** [comment]
Currently finding a way to effectively paginate for GET request.

The method introduced in the documentation is to use `orderBy` and `startAt`, but there is a problem: how can I get the correct data to for `startAt`.

For example, if I want the 10th to 20th comment, I can build a query like this:

```ts
COMMENTS_COLLECTION
  .where("pageId", "===", pageId)
  .orderBy("date", "desc")
  .startAt(dateOf10thComment)
  .limit(10)
```

A more simple solution is just query the all comments, then slice the result. It will be slower though.

**Comment by joulev** [comment]
> The method introduced in the documentation is to use orderBy and startAt, but there is a problem: how can I get the correct data to for startAt.

When I planned the feature I supposed we would be having a `commentIds` array for each page, something like

```ts
const pageData = await getDocumentInTransactionWithUid<Page>(t, pageRef, uid);
console.log(pageData.commentIds);
// ["id1", "id2", "id3"] etc
```

then we can simply take a slice of that array and `COMMENTS_COLLECTION.where("commentId", "==", commentId)` accordingly. Save time for users, save read operation count for us.

Now when I look back at how we implement it, while reading the documentation, there's no straightforward way to do this. Maybe let's remove the pagination query.

I mean if we have to query all comments anyway, pagination is useless.

**Comment by VietAnh1010** [comment]
Start working on notification.

The only kind of notification we will support currently is new comment notifications.

Is there any other kind of notification we will need to support?

**Comment by joulev** [comment]
No, for now. Except of course the welcome notification but it should be easy.
