### ISSUE TITLE
Google can override GitHub as auth provider as GitHub's emails are not verified

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#222]
Steps to reproduce:

* Change GitHub email to same email as Google email
* Sign up with GitHub
* Sign out
* Sign up with Google (same email)
* Now GitHub would be **unlinked** and Google substitutes it as the auth provider

This is [default Firebase behaviour](https://stackoverflow.com/a/46459975), and is generally good to have, since having users with unverified email accounts is bad.

However, for our use case, we don't need to care about email verification state. So this is bad.

To prevent this behaviour, we can set user email to verified on creation, regardless of auth provider. That would require `firebase-admin` though.

I suggest a route that I can fetch every time a new account is created. On that route you would set `emailVerified` to `true`.

**Comment by VietAnh1010** [comment]
This is easy. I will create `users/:uid/verify-email` for this purpose.

What kind of requests will be permitted for this route? `PUT` seems to be reasonable here.

**Comment by joulev** [comment]
Yeah `PUT` looks good to me. It's idempotent, so better than `POST` here.

**Comment by VietAnh1010** [comment]
Done.

Can you test the endpoint, especially its performance? On my local machine, it took about 1600 - 2000 ms for each request to this endpoint, which is extremely slow.

The reason is probably because my network connection is slow during these few days (I don't know what cause this tho).

**Comment by joulev** [comment]
> Done.
> 
> Can you test the endpoint, especially its performance? On my local machine, it took about 1600 - 2000 ms for each request to this endpoint, which is extremely slow.

The performance is not necessary actually, since it will be ran in the background after user creation. And there's no way a typical user can reproduce the problem during that 2 seconds.
> 
> The reason is probably because my network connection is slow during these few days (I don't know what cause this tho).

The f*cking sharks again, of course. https://vnexpress.net/cap-quang-bien-apg-dut-4492470.html

**Comment by joulev** [comment]
It's pretty fast on my computer, don't worry. (After all there are no complex logics behind this, if it's slow that means Firebase itself is slow [which is sadly true].)

**Comment by joulev** [comment]
I linked too late :(
