### ISSUE TITLE
"Last modified" dates

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#223]
It normally makes sense to sort sites/pages by modified dates, so that pages with newest updates show up at the top.

Is this already available/built-in in Firebase? Like `site.lastModified`...

Otherwise having it would be good.

**Comment by VietAnh1010** [comment]
What is exactly `modified date` here?

Suppose I have a page. Let say, I post a comment to that page, and then I update the page's title. Then what is the last modified date in this case?

**Comment by joulev** [comment]
I would expect it to be the timestamp of the title update action. BUT you decide; I will shape the wording on frontend accordingly. (Like from "Last updated 3 months ago" to "Last comment 3 months ago")

**Comment by VietAnh1010** [comment]
Okay, I will sort them by the timestamp of the update action, not the post comment action.

But how about we sort the pages/sites by its creation date?

**Comment by joulev** [comment]
Sorting is done on frontend :) you only need to provide a timestamp for me to do so.

**Comment by VietAnh1010** [comment]
Okay, I will add another field into site and page document: `lastUpdated`

**Comment by VietAnh1010** [comment]
Currently, adding another field is fine as we don't have much data in our database.

In the future, this is a breaking change and we cannot do that.

**Comment by joulev** [comment]
In the future, for issues like this we can do something like looping over all pages and set updated date to 01/01/1970 (Unix epoch).
