### ISSUE TITLE
Testing API routes

### ISSUE THREAD

**Issue by VietAnh1010** [joulev/ezkomment#92]
We will need to write tests to ensure the correct behaviors of API middlewares and handlers.

Firebase local emulator will probably be used. Messing with actual data on Firestore to test is NOT a good idea.

**Comment by VietAnh1010** [comment]
How to setup the testing environment only _once_, before all the test cases run? (I need to import data into the Local Emulator)

And is there an option to just _partially_ run the test suites?

Currently reading `Jest` documentation, hope that I can find the answer.

**Comment by joulev** [comment]
> And is there an option to just partially run the test suites?

`yarn test` runs only changed tests (according to `git`). It also “watches” the changes automatically.

**Comment by VietAnh1010** [comment]
I found the answer. 

Using `--testPathPattern`, I don't have to touch the client tests (which should always pass).

The new problem is how can I load environment variables? One solution is to use a setup file (Does `next` have a module to load environment variables. If yes, I don't need to add `dotenv` as another dependency - the setting will be much more elegant).

I will also use the setup file to load data into the databases before any test.

**Comment by joulev** [comment]
> Using `--testPathPattern`, I don't have to touch the client tests (which should always pass).

Hmm as I said, there is no need for this since `yarn test` will automatically ignore any tests whose content and dependencies are unchanged. For example on my branch with no tests changed, this is how it looks like:

```sh
$ yarn test
No tests found related to files changed since last commit.
Press `a` to run all tests, or run Jest with `--watchAll`.
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------

Watch Usage
 › Press a to run all tests.
 › Press f to run only failed tests.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press q to quit watch mode.
 › Press Enter to trigger a test run.
```

It will keep looking for any changes in the test files (and the files those tests import), so you can simply leave the terminal open.

If any, please don't use `--testPathPattern` because I need `yarn test` and `yarn test:ci` commands untouched and frontend tests should be executed in all CI runs.

> The new problem is how can I load environment variables?

[This](https://nextjs.org/docs/basic-features/environment-variables#test-environment-variables) may be helpful. I have never actually used it though.

**Comment by VietAnh1010** [comment]
I will create new commands to run API test suites, as I need to start Firebase Emulator and load documents to the database.

**Comment by VietAnh1010** [comment]
Still have some a problem with Jest.

`testEnvironment: "jest-environment-jsdom"` does not recognize the `export {};` syntax. Changing it to `node` works.

**Comment by joulev** [comment]
Rebase your branch to e116dabea74306f23d22c9cd83fd6e92e2629143 and use `--env=node` in your Jest command.
