### ISSUE TITLE
Routes to upload images

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#98]
We should stick to JSON as much as possible in FE-BE communication, however that's not always possible.

* [x] Create a route to upload/update user photo (f8b98f5).
* [x] Create a route to upload/update site identification photo (f8b98f5).

Each of these route should expect a `PUT`/`PATCH` with the body being a file.

```ts
// photo: File
const form = new FormData();
form.append("photo", photo);
await fetch("url", {
  method: "PUT",
  headers: { /* auth */ },
  body: form,
});
```

**Comment by VietAnh1010** [comment]
After a photo is uploaded, where will we store it?

**Comment by joulev** [comment]
[Firebase Storage](https://firebase.google.com/docs/storage).

**Comment by VietAnh1010** [comment]
In what format will the photo be uploaded, byte stream?

**Comment by joulev** [comment]
In a nutshell, as follows. I have used [`formidable`](https://www.npmjs.com/formidable) to parse these requests before and it works well.

```ts
async function updatePhoto(photo: File) {
    const form = new FormData();
    form.append("photo", photo);
    await fetch("/api/hello", { method: "PUT", body: form });
}
```

If you need it, I will prepare a temporary page with an upload button for you to test.

**Comment by joulev** [comment]
If you are working on this do remember to update the status of this issue in the [Projects](https://github.com/joulev/ezkomment/projects).

**Comment by VietAnh1010** [comment]
Firebase Admin cannot [get download URL](https://stackoverflow.com/questions/42956250/get-download-url-from-file-uploaded-with-cloud-functions-for-firebase?noredirect=1&lq=1) after a photo is uploaded. I will just expose the public URL right now, but it is not very secure.

**Comment by joulev** [comment]
No need to secure photos I think. No one can guess those URLs anyway. (Yeah I’m careless but *that* level of security is unnecessary.)

**Comment by VietAnh1010** [comment]
Done, we will use public URL at the moment (I still prefer download URL, will look for a way if I have time). Will implement extra logics (updates photoURL, iconURL, deletes photo and icon when delete user or site) before processing the next PR.

**Comment by joulev** [comment]
The photo is displayed with a normal image tag, which requires an URL. I think that URL should be randomised enough to make it impossible to guess, but if someone manages to get it, they will certainly be able to view it themselves.

I don’t download the image as blob since it won’t be performant.

That’s why I don’t actually think it’s a good idea to hide the photo behind any authentication.

Look: https://avatars.githubusercontent.com/VietAnh1010 is your avatar and I don’t need your GitHub password to view it. If GitHub is fine with it I’m fine.

**Comment by joulev** [comment]
If you check the checklist, accompany it with a git hash to indicate the exact commit you implemented the fix/feature. I have unchecked the checklist above.
