### ISSUE TITLE
Fully type the routes

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#99]
Next.js's `NextApiResponse` type takes an optional argument. That argument, default to `any`, is the type of the response JSON and can be used to type API routes.

```ts
// types/utils
type ApiError = { msg: string; code: string };
type ApiResponse<T = any> = NextApiResponse<T | ApiError>;

// route
type Res = { uid: string; displayName: string };
const handler = (_: NextApiRequest, res: ApiResponse<Res>) => {
  res.status(500).json({ msg: "blah" }); // error
  res.status(500).json({ msg: "blah", code: "bleh" }); // ok
  res.status(200).json({ uid: "abc123" }); // error
  res.status(200).json({ uid: "abc123", displayName: "John Doe" }); // ok
}
```

May be a good idea to fully type the backend this way.

**Comment by VietAnh1010** [comment]
Good suggestion, I will add this.

**Comment by joulev** [comment]
Only close this when you have finished or decided not to do it :)

**Comment by VietAnh1010** [comment]
Finished it, close this issue.

**Comment by joulev** [comment]
Since this hasn't landed on `main` yet, for the purpose of tracking I'm reopening this. [Link your PR with this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to have this issue closed as soon as the PR is merged.

**Comment by joulev** [comment]
Sorry, forgot to check this issue in #121. It has been fixed in that PR.
